tonnie/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tonnieapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tonnieapp/urls.py
from django.urls import path
from .import views

app_name = 'tonnieapp'
urlpatterns = [
    path('',views.MemberListView.as_view(),name='index'),
    path('add-member', views.MemberCreateView.as_view(), name='add-member'),
    path('<int:pk>/update', views.MemberUpdateView.as_view(),name='update-member'),
    path('<int:pk>/delete',views.MemberDeleteView.as_view(),name='delete-member'),

]

tonnieapp/models.py
from django.db import models
from django.shortcuts import  reverse

# Create your models here.
class Member(models.Model):
    name= models.CharField(max_length=40)
    age= models.IntegerField()
    nationality= models.CharField(max_length=40)
    primary= models.CharField(max_length=40)
    secondary= models.CharField(max_length=40)
    email= models.EmailField()
    occupation=models.CharField(max_length=50)
    slogan=models.CharField(max_length=50)
    residence = models.CharField(max_length=50)
    photo=models.ImageField()
    campus = models.CharField(max_length=50)
    course = models.CharField(max_length=50)
    hobby = models.CharField(max_length=50)
    is_male=models.BooleanField(default=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('tonnieapp:index')

tonnieapp/views.py
from django.shortcuts import render
from .models import Member
from  django.views.generic import ListView,CreateView, UpdateView, DeleteView

# Create your views here.
# def index(request):
#     profiles =Member.objects.all()
#     return render(request,'tonnieapp/index.html',{'profiles':profiles})
class MemberListView(ListView):
    model = Member
    template_name = 'tonnieapp/index.html'
    context_object_name = 'profiles'
    orderring = ['name']

    def get_queryset(self):
        query = self.request.GET.get('q')
        if query:
            return Member.objects.filter(name__icontains=query)| Member.objects.filter(occupation__icontains=query)
        else:
            return Member.objects.all()

class MemberCreateView(CreateView):
    model = Member
    fields = '__all__'

class MemberUpdateView(UpdateView):
    model = Member
    fields = '__all__'

class MemberDeleteView(DeleteView):
    model = Member
    success_url = '/'

tonnieapp/templates/tonnieapp/base.html
<html lang="en">

<head>

<title>{% block title %}{% endblock %}</title>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

<link href='https://fonts.googleapis.com/css?family=Modak' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Sofia' rel='stylesheet'>
<link href='https://fonts.googleapis.com/css?family=Akronim' rel='stylesheet'>

{% load static %}
  <link rel="stylesheet" href="{% static 'tonnieapp/css/style.css' %}" type="text/css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.0/jquery.min.js"></script>



<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>



<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">

    <span class="navbar-toggler-icon"></span>

  </button>

  <a class="navbar-brand" href="{% url 'tonnieapp:index' %}" style="font-family: 'Acme', cursive;">PYTHON MEMBERS</a>



  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">

    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

    <li class="nav-item">

    <form class="form-inline my-2 my-lg-0">

      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="q" value="{{ request.GET.q }}">

      <button class="btn btn-outline-info my-2 my-sm-0" type="submit">Search</button>

    </form>

        </li>

    </ul>

    <ul class="navbar-nav">

        <li class="nav-item active">

      <a class="nav-link" href="{% url 'tonnieapp:add-member' %} " style="font-family: 'Orbirton', cursive;"><i class="fas fa-user-plus" style="color: steelblue;"></i> Add Member<span class="sr-only">(current)</span></a>

      </li>

      <li class="nav-item active">

      <a class="nav-link" href="" style="font-family: 'Orbirton', cursive;"><i class="fas fa-sign-out-alt" style="color: red;"></i> Logout<span class="sr-only">(current)</span></a>

      </li>



    </ul>

  </div>

</nav>

<div class="container">


    {% block content %}



    {% endblock %}





</div>







</body>

tonnieapp/templates/tonnieapp/index.html
{% extends 'tonnieapp/base.html' %}
{% block title %}Python Members{% endblock %}
{% block content %}
        <div class="row">
            {%if profiles%}
                {% for prof in profiles%}
                    <div class="col-sm-3">
                         <div class="card card-body my-1">
                            <h4 class="text-center"style="white-space: nowrap;
                            overflow: hidden;
                            text-overflow: ellipsis; max-width:90%;
                            border-bottom: 1px solid black; font-family: Modak;">{{ prof.name }}</h4>

                        <div class="card card-body my-2"style="background-color: {% if prof.is_male %}orange; {% else %}red;{% endif %}">


                            <img src="{{prof.photo.url}}" class="rounded-circle mx-auto img-fluid" alt="" style="height:200px; width:200px;">
                            <div class="caption">
                                <h5 class="text-center">{{prof.occupation}}</h5>
                                 <h6 class="text-center"style="white-space: nowrap;overflow: hidden;text-overflow: ellipsis; max-width: 90%;font-family: Sofia;">{{prof.slogan}}</h6>
                                 <button class="btn btn-info btn-sm" data-toggle="modal" data-target="#modal-{{prof.id}}">
                                    <i class="fas fa-info"></i>
                                 </button>
                                 <a href="{% url 'tonnieapp:delete-member' prof.id %}" class="btn btn-danger btn-sm" style="float:right;">
                                    <i class="fas fa-trash"></i>
                                 </a>

                             </div>
                            </div>
                        </div>
                        <!--Modal-->
                        <div class="modal fade " id="modal-{{prof.id}}" role="dialog">
                            <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">

                                         <button type="button" class="close" data-dismiss="modal">&times;</button>
                                </div>

                             <div class="modal-body"style="font-family: Akronim;">

                                 <p>{{ prof.name }}is {{ prof.age }} years.{{ prof.name }} is a{{ prof.nationality }} citizen.
                                     {{ prof.name }} went to {{ prof.primary }} then later joined {{ prof.secondary}} secondary school.
                                     {{ prof.name }} is a {{ prof.occupation }}.
                                     {{ prof.name }}lives in {{ prof.residence }}.
                                     You can easily reach her via her email <a href="mailto:  {{prof.email }}">{{ prof.email }}</a>.
                                     {{ prof.name }} slogan is {{ prof.slogan}}.
                                     Currently  she is a student at {{ prof.campus }}
                                     pursuing {{ prof.course}} degree.{{ prof.name }} enjoys {{ prof.hobby}}.
                                 </p>

                             </div>
                             <div class="modal-footer">
                                <a href="{% url 'tonnieapp:update-member' prof.id %}" class="btn btn-outline primary btn-sm">
                                  <i class="fas fa-edit"></i>
                                </a>
                             </div>
                    </div>
                            </div>
                        </div>
                        </div>

                 {%endfor %}
            {%endif %}
        </div>
{% endblock %}


</body>
</html>

tonnieapp/templates/tonnieapp/member_confirm_delete.html
{% extends 'tonnieapp/base.html' %}
{% block title %}Delete{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-sm-3"></div>
        <div class="col-sm-6">
            <div class="card card-body my-1">
                <h3>Delete<b>{{ object.name }}</b>?</h3>
                <hr>
                <form method="post" class="form-horizontal">
                    {% csrf_token %}
                    <div class="form-group">
                        <button type="submit" class="btn btn-danger" >Delete</button>
                        <a href="{% url 'tonnieapp:index' %}" class="btn btn-secondary">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

tonnieapp/templates/tonnieapp/member_form.html
{% extends 'tonnieapp/base.html' %}
{% load crispy_forms_tags %}


{% block title %}{%if object %}Update{{ object.name }}{% else %}Add Member{% endif %}

{% block content %}
    <div class="row">
        <div class="col-sm-3"></div>
          <div class="col-sm-6">
              <div class="card card-body">
                  <h3 class="text-capitalize">{% if object %}Update {{ object.name }}{% else %}Add Member{% endif %}</h3>
                  <hr>
                  <form method="post" enctype="multipart/form-data">
                      {%csrf_token%}
                      {{form |crispy}}
                      <div class="form-group">
                          <button type="submit" class="btn btn-info">Submit</button>
                      </div>
                  </form>
              </div>
          </div>
        <div class="col-sm-3"></div>
    </div>
{% endblock %}
{% endblock %}